spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hospitaldb
    username: hospital
    password: hospital
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
